jobs:
- name: deploy-opsman
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsman-product
      params:
        globs:
        - '*.ova'
      passed:
      - regulator
      resource: pcf-ops-manager
      trigger: true
  - file: pcf-pipelines/install-pcf/vsphere/tasks/import-opsman/task.yml
    task: deploy
- name: regulator
  plan:
  - get: schedule
    trigger: true
  - get: pcf-pipelines-pivnet
    params:
      globs: []
    trigger: true
  - get: pivnet-opsman-product
    params:
      globs: []
    resource: pcf-ops-manager
resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
resources:
- name: pcf-pipelines
  source:
    branch: master
    private_key: {{git_private_key}}
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
  type: git
- name: pcf-ops-manager
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver
  type: pivnet
- name: schedule
  source:
    interval: 30m
    location: America/Denver
    start: 12:00 AM
    stop: 11:59 PM
  type: time
- name: pcf-pipelines-pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: {{pivnet_product_slug}}
    sort_by: semver
  type: pivnet
